<?php
require __DIR__.'/../api/bootstrap.php';
require_once __DIR__.'/../includes/site-shell.php';
function e($v){return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');}
$collections=[
 ['Productivity','Knowledge bases, planners and weekly systems.','📚','42 resources','Build a calm creator workflow'],
 ['Design','Covers, portfolios and visual templates.','🎨','28 resources','Polish your brand assets'],
 ['Launch','SaaS, offer and product launch kits.','🚀','19 resources','Ship faster with checklists'],
 ['Business','Finance, client and founder systems.','💰','31 resources','Run the operating side'],
 ['AI','Prompts, automations and AI workflows.','🤖','24 resources','Use AI with structure'],
 ['Marketing','Calendars, hooks, campaigns and content systems.','📣','35 resources','Publish with consistency'],
];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collections · NexShelfy</title><meta name="description" content="Browse NexShelfy free resources by outcome and category."><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/content-platform.css?v=20260715-shared-polish"><link rel="stylesheet" href="/assets/nexshelfy-app.css?v=20260715-shared-polish"><link rel="stylesheet" href="/assets/nexshelfy-shop-fixes.css?v=20260717-final-ui-2"></head><body class="cp-page ns-unified-page ns-collections-page ns-collections-premium-page"><?php ns_site_header('collections'); ?><main class="cp-shell ns-collections-main"><section class="ns-split-hero ns-collection-hero-v2"><div class="ns-split-copy"><div class="cp-kicker">Curated shelves</div><h1>Find resources by the outcome you want.</h1><p>Choose a collection, then open a focused shelf of free products, templates, systems and guides.</p><form class="ns-glass-search" action="/shop/" method="get"><input name="q" name="q" placeholder="Filter collections or search resources"><button class="ns-btn" type="submit">Search library</button></form><div class="ns-trust-pills"><span>Hand-picked</span><span>Free downloads</span><span>Updated July 2026</span></div></div><div class="ns-hero-featured-card ns-collection-feature-card"><div class="ns-card-pills"><span>6 core collections</span><span>170+ resources indexed</span></div><h2>A cleaner way to browse.</h2><p>Each shelf leads to filtered products, so visitors do not feel lost in one huge library.</p><a class="ns-btn" href="/shop/">Browse all resources →</a></div></section><section class="ns-blog-section ns-collection-section-v2"><div class="ns-section-title"><span>Collections</span><h2>Choose your starting point</h2><p>Equal-height cards with resource counts, clearer CTAs and fast filtering.</p></div><div class="ns-collection-grid ns-collection-grid-premium ns-outcome-grid"><?php foreach($collections as $c): ?><a href="/shop/?q=<?=rawurlencode($c[0])?>"><span><?=e($c[2])?></span><strong><?=e($c[0])?></strong><small><?=e($c[1])?></small><b><?=e($c[3])?></b><em><?=e($c[4])?> →</em></a><?php endforeach; ?></div></section></main><?php ns_site_footer(); ?><script src="/assets/nexshelfy-app.js?v=20260717-final-ui-2"></script></body></html>
