<?php
require __DIR__.'/../api/bootstrap.php';
require_once __DIR__ . '/includes/site-shell.php';
ensure_nexshelfy_serious_schema();
$slug=clean((string)($_GET['slug']??''),180);
$st=db()->prepare('SELECT * FROM products WHERE slug=? AND status="active" LIMIT 1');$st->execute([$slug]);$p=$st->fetch();
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
if(!$p){http_response_code(404);exit('Product not found.');}
$relatedSt=db()->prepare('SELECT id,slug,name,description,cover_image,download_count,created_at FROM products WHERE status="active" AND id<>? ORDER BY id DESC LIMIT 3');$relatedSt->execute([(int)$p['id']]);$related=$relatedSt->fetchAll();
$description=$p['description'] ?: 'A curated NexShelfy digital product.';$downloads=(int)($p['download_count']??0); if($downloads<1)$downloads=2300+(int)$p['id']*73;
$canonical='https://nexshelfy.com/shop/'.rawurlencode((string)$p['slug']).'/';
function footer_html(){ob_start(); ?><?php ns_site_footer(); ?><?php return ob_get_clean();}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($p['name'])?> · NexShelfy</title><link rel="canonical" href="<?=e($canonical)?>"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta name="description" content="<?=e($description)?>"><meta property="og:title" content="<?=e($p['name'])?> · NexShelfy"><meta property="og:description" content="<?=e($description)?>"><meta property="og:url" content="<?=e($canonical)?>"><meta property="og:type" content="product"><link rel="stylesheet" href="/assets/content-platform.css?v=20260712-global-footer-card-polish"><link rel="stylesheet" href="/assets/nexshelfy-app.css?v=20260712-global-footer-card-polish"><link rel="stylesheet" href="/assets/nexshelfy-shop-fixes.css?v=20260717-final-ui-2"></head>
<body class="cp-page ns-product-detail-page ns-unified-page"><?php ns_site_header('shop'); ?>
<main class="cp-shell ns-product-shell"><nav class="ns-breadcrumb"><a href="/">Home</a><span>›</span><a href="/shop/">Free Products</a><span>›</span><span><?=e($p['name'])?></span></nav><section class="ns-product-hero-premium"><div class="ns-product-copy"><div class="ns-card-pills"><span>FREE</span><span><?=e(str_contains(strtolower($p['name'].$p['description']),'notion')?'Notion':'Resource')?></span><span>Email-gated download</span></div><h1><?=e($p['name'])?></h1><p><?=e($description)?></p><div class="ns-rating-row"><b>★★★★★</b><span>Downloaded by <?=number_format($downloads)?>+ creators</span></div><div class="cp-actions ns-product-actions"><a class="cp-btn primary ns-free-download" href="/api/free-download.php?type=product&amp;slug=<?=rawurlencode($p['slug'])?>">Download</a><button class="cp-btn" data-ns-product-save data-slug="<?=e($p['slug'])?>">♡ Save</button><button class="cp-btn" data-share>↗ Share</button></div><div class="ns-trust-pills"><span>✔ Free forever</span><span>✔ Instant access</span><span>✔ Lifetime updates</span><span>✔ No spam</span></div></div><div class="ns-product-preview-stack"><div class="ns-device-mock laptop"><div><span><?=e($p['name'])?></span><i></i><i></i><i></i></div></div><div class="ns-device-mock tablet"><div></div></div><div class="ns-device-mock phone"><div></div></div></div></section>
<section class="ns-preview-gallery"><div class="ns-section-title"><span>Preview</span><h2>See what is inside</h2></div><div class="ns-gallery-grid"><div><b>Dashboard</b><p>Main workspace preview</p></div><div><b>Databases</b><p>Linked notes and resources</p></div><div><b>Workflow</b><p>Ready-to-use structure</p></div><div><b>Documentation</b><p>Setup and examples</p></div></div></section>
<section class="ns-product-content-grid"><div><section class="cp-body ns-product-body"><h2>Everything included</h2><ul class="ns-feature-list"><li><?=e($p['name'])?> quick-start file or link</li><li>Setup notes matched to this resource</li><li>Reusable workflow examples</li><li>Helpful categories and structure</li><li>Practical creator-ready system</li><li>Documentation and update notes</li></ul><h2>Who is this template for?</h2><p>This resource is useful for creators, founders, freelancers and students who want a practical way to use <?=e($p['name'])?> in their real workflow.</p><h2>How to use this template</h2><p>Download the resource, read the setup notes, then adapt the sections and categories to your actual workflow.</p><h2>Why this saves time</h2><p>Instead of starting from a blank page, you begin with a curated structure and only customize the parts that matter.</p></section><section class="ns-testimonials"><h2>Creator feedback</h2><div class="ns-testimonial-grid"><blockquote>★★★★★<br>“This made the setup much faster.”<span>— Ahmed</span></blockquote><blockquote>★★★★★<br>“Clean, simple and actually useful.”<span>— Sarah</span></blockquote><blockquote>★★★★★<br>“A clean free resource I could actually use.”<span>— Ali</span></blockquote></div></section><section class="ns-faq"><h2>FAQ</h2><details open><summary>Can I use it commercially?</summary><p>You can use it for your own work and internal client workflow unless the product page states otherwise.</p></details><details><summary>Does this require Notion Pro?</summary><p>No. Most free resources are designed to work with free or common creator tools.</p></details><details><summary>How do I receive updates?</summary><p>Use your email during download and you may receive future version updates.</p></details></section></div><aside class="ns-product-side-card"><b>Product details</b><dl><div><dt>Price</dt><dd>FREE</dd></div><div><dt>Downloads</dt><dd><?=number_format($downloads)?>+</dd></div><div><dt>Version</dt><dd>1.2</dd></div><div><dt>Updated</dt><dd><?=date('M Y',strtotime($p['created_at']?:'now'))?></dd></div><div><dt>File type</dt><dd><?=!empty($p['resource_link'])?'Link':'PDF / ZIP'?></dd></div><div><dt>Size</dt><dd>2–12 MB</dd></div><div><dt>License</dt><dd>Personal use</dd></div></dl><a class="cp-btn primary ns-free-download" href="/api/free-download.php?type=product&amp;slug=<?=rawurlencode($p['slug'])?>">Download</a><div class="ns-product-tags"><a><?=e(str_contains(strtolower($p['name'].$p['description']),'notion')?'Notion':'Resource')?></a><a>Template</a><a>Creator system</a><a>Free download</a></div></aside></section>
<section class="ns-blog-section"><div class="ns-section-title"><span>Related Articles</span><h2>Learn how to use it better</h2></div><div class="ns-blog-lanes"><div><span>Guide</span><h3>How to build a second brain</h3><p>Turn scattered notes into a practical workspace.</p></div><div><span>Productivity</span><h3>Best PKM systems</h3><p>Simple structures for notes, learning and projects.</p></div><div><span>Notion</span><h3>Notion productivity guide</h3><p>Use dashboards without overcomplicating your setup.</p></div></div></section>
<?php if($related):?><section class="cp-related-posts"><div class="cp-kicker">More free products</div><div class="cp-section-heading"><h2>Recommended downloads</h2><a href="/shop/">View all →</a></div><div class="cp-related-grid"><?php foreach($related as $i=>$rp):?><article class="cp-related-card ns-premium-resource-card"><a href="/shop/<?=e($rp['slug'])?>/" class="cp-related-cover ns-resource-cover"><span>FREE</span><strong><?=e($rp['name'])?></strong></a><div><p><?=e($rp['description'])?></p><div class="ns-post-metrics"><span><?=number_format(((int)($rp['download_count']??0)?:1200+$i*500))?> downloads</span></div><a href="/shop/<?=e($rp['slug'])?>/">Open product →</a></div></article><?php endforeach;?></div></section><?php endif;?></main><div class="ns-sticky-download"><b><?=e($p['name'])?></b><span>FREE</span><a class="ns-free-download" href="/api/free-download.php?type=product&amp;slug=<?=rawurlencode($p['slug'])?>">Download</a></div><?=footer_html()?><script src="/assets/nexshelfy-app.js?v=20260712-global-footer-card-polish"></script></body></html>
