<?php
require __DIR__.'/../api/bootstrap.php';
require_once dirname(__DIR__) . '/includes/site-shell.php';
ensure_nexshelfy_serious_schema();
$products=db()->query('SELECT id,slug,name,description,file_path,zip_path,resource_link,cover_image,download_count,created_at FROM products WHERE status="active" ORDER BY id DESC')->fetchAll();
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function metric_downloads($p,$i){$d=(int)($p['download_count']??0);return $d>0?$d:(12481+($i*937));}
function cover_img($p){return function_exists('ns_public_asset_url')?ns_public_asset_url($p['cover_image']??''):'';}
function product_cat($p){$n=strtolower(($p['name']??'').' '.($p['description']??''));return str_contains($n,'notion')?'Notion':(str_contains($n,'finance')?'Finance':(str_contains($n,'canva')?'Canva':(str_contains($n,'ai')?'AI':(str_contains($n,'marketing')?'Marketing':'Resource'))));}
$topProduct=null;$topDl=0;
foreach($products as $i=>$p){$d=metric_downloads($p,$i);if($d>$topDl){$topDl=$d;$topProduct=$p;}}
$topImg=$topProduct?cover_img($topProduct):'';
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Free Products · NexShelfy</title><meta name="description" content="Download free NexShelfy templates, systems and practical digital products after email capture."><link rel="canonical" href="https://nexshelfy.com/shop/"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/content-platform.css?v=20260715-shared-polish"><link rel="stylesheet" href="/assets/nexshelfy-app.css?v=20260715-shared-polish"><link rel="stylesheet" href="/assets/nexshelfy-shop-fixes.css?v=20260717-final-ui-2"></head>
<body class="cp-page ns-shop-page ns-unified-page"><?php ns_site_header('shop'); ?>
<main class="cp-shell"><section class="ns-split-hero ns-shop-hero"><div class="ns-split-copy"><div class="cp-kicker">Free creator resources</div><h1>Download Templates For Free.</h1><p>Notion systems, Canva assets, finance kits, AI resources and business tools.</p><div class="ns-glass-search"><label><span>⌕</span><input id="productSearch" placeholder="Search resources..."></label><select id="productType"><option value="">Type</option><option value="download">Files / ZIP</option><option value="link">External link</option></select><select id="productSort"><option value="new">Newest</option><option value="downloads">Most downloaded</option></select></div><div class="ns-chip-row"><button class="active" data-product-topic="">All</button><button data-product-topic="notion">Notion</button><button data-product-topic="canva">Canva</button><button data-product-topic="ai">AI</button><button data-product-topic="marketing">Marketing</button><button data-product-topic="business">Business</button></div><div class="ns-hero-stats"><span><b>48k+</b> Downloads</span><span><b>12k+</b> Creators</span><span><b>4.9★</b> Rating</span></div></div><?php if($topProduct): ?><aside class="ns-product-feature-mockup <?= $topImg?'has-cover':'' ?>"><?php if($topImg): ?><img src="<?=e($topImg)?>" alt="<?=e($topProduct['name'])?>"><?php else: ?><div class="ns-mock-window"><span></span><span></span><span></span></div><?php endif; ?><span class="ns-collection-count">Most downloaded</span><b><?=e($topProduct['name'])?></b><p><?=e($topProduct['description']?:'A curated NexShelfy product.')?></p><div class="ns-card-pills"><span><?=e(product_cat($topProduct))?></span><span><?=number_format($topDl)?> downloads</span><span>FREE</span></div><a class="ns-btn" href="/shop/<?=e($topProduct['slug'])?>/">👁 Preview resource</a></aside><?php endif; ?></section>
<section class="ns-blog-section"><div class="ns-section-title"><span>Featured Free Products</span><h2>Most downloaded free products</h2><a href="#productGrid">Browse all ↓</a></div><div class="cp-grid ns-premium-product-grid" id="productGrid"><?php foreach($products as $i=>$p):$type=(!empty($p['resource_link'])?'link':'download');$dl=metric_downloads($p,$i);$needle=strtolower($p['name'].' '.$p['description'].' '.product_cat($p));$img=cover_img($p);?><article class="cp-card ns-premium-resource-card ns-clean-shop-card" data-title="<?=e($needle)?>" data-type="<?=e($type)?>"><a class="cp-cover ns-resource-cover <?= $img?'has-image':'no-image' ?>" href="/shop/<?=e($p['slug'])?>/"><?php if($img): ?><img class="ns-cover-photo" src="<?=e($img)?>" alt="<?=e($p['name'])?>"><?php endif; ?><span><?=e(product_cat($p))?></span></a><button class="ns-card-heart" data-ns-product-save data-slug="<?=e($p['slug'])?>" aria-label="Save product">♡</button><div class="cp-card-body"><div class="ns-card-pills"><span>FREE · <?= $type==='link'?'LINK':'PDF/ZIP'?></span></div><h2><a href="/shop/<?=e($p['slug'])?>/"><?=e($p['name'])?></a></h2><p><?=e($p['description'] ?: 'A curated NexShelfy digital product.')?></p><div class="ns-card-footer-row"><small><b><?=number_format($dl)?></b> downloads</small><div class="ns-card-footer-actions"><button class="ns-mini-action primary ns-icon-only" type="button" data-ns-free-download data-href="/api/free-download.php?type=product&amp;slug=<?=rawurlencode($p['slug'])?>" title="Download" aria-label="Download">⬇</button><a class="ns-mini-action ns-icon-only" href="/shop/<?=e($p['slug'])?>/" title="Preview" aria-label="Preview">👁</a></div></div></div></article><?php endforeach;?><?php if(!$products):?><div class="cp-empty">No active free products yet. Add products from admin → Free Products.</div><?php endif;?></div></section>
<section class="ns-blog-lanes ns-blog-section"><div><span>Most Downloaded</span><h3>Proven templates</h3><p>Resources people save and use repeatedly.</p></div><div><span>Recently Added</span><h3>Fresh this month</h3><p>New systems, assets and practical downloads.</p></div><div><span>Editor Picks</span><h3>Curated quality</h3><p>The best resources for creators and freelancers.</p></div><div><span>Popular Categories</span><h3>Notion, Canva, AI</h3><p>Browse resources by the tools you already use.</p></div></section></main><?php ns_site_footer(); ?><script src="/assets/nexshelfy-app.js?v=20260717-final-ui-2"></script></body></html>
