<?php
require __DIR__.'/../api/bootstrap.php';
require_once dirname(__DIR__) . '/includes/site-shell.php';
ensure_nexshelfy_serious_schema();
$resources=db()->query('SELECT id,title,slug,description,file_path,zip_path,resource_link,resource_type,cover_image,download_count,created_at FROM content_resources WHERE status="active" ORDER BY id DESC')->fetchAll();
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function cover_img($r){return function_exists('ns_public_asset_url')?ns_public_asset_url($r['cover_image']??''):'';}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Free Resources · NexShelfy</title><meta name="description" content="Free creator hooks, content templates, swipe files and practical resources."><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/content-platform.css?v=20260715-shared-polish"><link rel="stylesheet" href="/assets/nexshelfy-app.css?v=20260715-shared-polish"><link rel="stylesheet" href="/assets/nexshelfy-shop-fixes.css?v=20260717-final-ui-2"></head>
<body class="cp-page ns-unified-page ns-resources-page"><?php ns_site_header('resources'); ?>
<main class="cp-shell"><section class="ns-split-hero"><div class="ns-split-copy"><div class="cp-kicker">Hooks, templates and creator assets</div><h1>Free resources for content, systems and smarter creator work.</h1><p>This library is for hooks, prompts, swipe files, content frameworks and practical reference material.</p><div class="ns-glass-search"><label><span>⌕</span><input id="resourceSearch" placeholder="Search resources..."></label></div></div><aside class="ns-product-feature-mockup"><b>Free Resources</b><p>Hooks, templates, swipe files, checklists and useful creator content.</p><div class="ns-card-pills"><span>Content</span><span>Templates</span><span>FREE</span></div></aside></section>
<section class="ns-blog-section"><div class="ns-section-title"><span>Resource Library</span><h2>Download free resources</h2><a href="/shop/">Need digital products?</a></div><div class="cp-grid ns-premium-product-grid" id="resourceGrid"><?php foreach($resources as $i=>$r):$type=!empty($r['resource_link'])?'Link':(!empty($r['zip_path'])?'ZIP':'File');$img=cover_img($r);?><article id="<?=e($r['slug'])?>" class="cp-card ns-premium-resource-card ns-clean-shop-card" data-title="<?=e(strtolower($r['title'].' '.$r['description'].' '.$r['resource_type']))?>"><a class="cp-cover ns-resource-cover <?= $img?'has-image':'no-image' ?>" href="/resources/<?=e($r['slug'])?>/"><?php if($img): ?><img class="ns-cover-photo" src="<?=e($img)?>" alt="<?=e($r['title'])?>"><?php endif; ?><span><?=e($r['resource_type']?:'Free Resource')?></span></a><div class="cp-card-body"><div class="ns-card-pills"><span>FREE · <?=e($type)?></span></div><h2><?=e($r['title'])?></h2><p><?=e($r['description'] ?: 'A practical free NexShelfy resource.')?></p><div class="ns-card-footer-row"><small><b><?=number_format((int)$r['download_count'])?></b> downloads</small><div class="ns-card-footer-actions"><a class="ns-mini-action ns-icon-only" href="/resources/<?=e($r['slug'])?>/" aria-label="Preview resource">↗</a><button class="ns-mini-action ns-icon-only" data-ns-resource-save data-slug="<?=e($r['slug'])?>" data-title="<?=e($r['title'])?>" aria-label="Save resource">♡</button><a class="ns-mini-action primary ns-icon-only" data-ns-direct-download href="/api/free-download.php?type=resource&amp;slug=<?=rawurlencode($r['slug'])?>" aria-label="Download resource">↓</a></div></div></div></article><?php endforeach;?><?php if(!$resources):?><div class="cp-empty">No active free resources yet. Add resources from admin → Resources.</div><?php endif;?></div></section></main>
<?php ns_site_footer(); ?><script src="/assets/nexshelfy-app.js?v=20260717-final-ui-2"></script><script>document.addEventListener('DOMContentLoaded',()=>{const q=document.getElementById('resourceSearch');q&&q.addEventListener('input',()=>{const term=q.value.toLowerCase();document.querySelectorAll('#resourceGrid article').forEach(card=>card.hidden=!(card.dataset.title||'').includes(term));});});</script></body></html>
