<?php
require __DIR__.'/../api/bootstrap.php';
require_once dirname(__DIR__) . '/includes/site-shell.php';
ensure_nexshelfy_serious_schema();
$slug=clean((string)($_GET['slug']??''),180);
$st=db()->prepare('SELECT * FROM content_resources WHERE slug=? AND status="active" LIMIT 1');$st->execute([$slug]);$r=$st->fetch();
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
if(!$r){http_response_code(404);exit('Resource not found.');}
$othersSt=db()->prepare('SELECT id,title,slug,description,resource_type,cover_image,download_count FROM content_resources WHERE status="active" AND id<>? ORDER BY download_count DESC,id DESC LIMIT 3');$othersSt->execute([(int)$r['id']]);$others=$othersSt->fetchAll();
$img=ns_public_asset_url($r['cover_image']??'');
$download='/api/free-download.php?type=resource&slug='.rawurlencode($r['slug']);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($r['title'])?> · NexShelfy</title><meta name="description" content="<?=e($r['description'])?>"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/content-platform.css?v=20260717-resource-detail"><link rel="stylesheet" href="/assets/nexshelfy-app.css?v=20260717-resource-detail"><link rel="stylesheet" href="/assets/nexshelfy-shop-fixes.css?v=20260717-resource-detail"></head>
<body class="cp-page ns-unified-page ns-resource-detail-page"><?php ns_site_header('resources'); ?><main class="cp-shell ns-resource-detail-shell"><nav class="ns-breadcrumb"><a href="/">Home</a><span>›</span><a href="/resources/">Free Resources</a><span>›</span><span><?=e($r['title'])?></span></nav><section class="ns-resource-detail-hero"><div class="ns-resource-detail-media <?php echo $img?'has-image':'no-image'; ?>"><?php if($img):?><img src="<?=e($img)?>" alt="<?=e($r['title'])?>"><?php else:?><span><?=e(strtoupper(substr($r['title'],0,1)))?></span><?php endif;?></div><div class="ns-resource-detail-copy"><div class="ns-card-pills"><span>FREE</span><span><?=e($r['resource_type']?:'Resource')?></span></div><h1><?=e($r['title'])?></h1><p><?=e($r['description']?:'A practical free resource for creators and small teams.')?></p><div class="ns-rating-row"><b><?=number_format((int)$r['download_count'])?></b><span>downloads</span></div><div class="cp-actions ns-product-actions"><a class="cp-btn primary" data-ns-direct-download href="<?=e($download)?>">Get Free</a><button class="cp-btn" data-ns-resource-save data-slug="<?=e($r['slug'])?>" data-title="<?=e($r['title'])?>">♡ Like</button><button class="cp-btn" data-share>↗ Share</button></div></div></section><section class="cp-body ns-resource-description"><h2>About this resource</h2><p><?=nl2br(e($r['description']?:'Use this resource as a practical starting point, then adapt it to your workflow.'))?></p></section><?php if($others):?><section class="cp-related-posts"><div class="cp-section-heading"><h2>Other free resources</h2><a href="/resources/">View all →</a></div><div class="cp-related-grid"><?php foreach($others as $o):$oi=ns_public_asset_url($o['cover_image']??'');?><article class="cp-related-card ns-premium-resource-card"><a href="/resources/<?=e($o['slug'])?>/" class="cp-related-cover ns-resource-cover <?= $oi?'has-image':'no-image' ?>"><?php if($oi):?><img class="ns-cover-photo" src="<?=e($oi)?>" alt="<?=e($o['title'])?>"><?php endif;?><span>FREE</span><strong><?=e($o['title'])?></strong></a><div><p><?=e($o['description'])?></p><div class="ns-post-metrics"><span><?=number_format((int)$o['download_count'])?> downloads</span></div><a href="/resources/<?=e($o['slug'])?>/">Preview →</a></div></article><?php endforeach;?></div></section><?php endif;?></main><?php ns_site_footer(); ?><script src="/assets/nexshelfy-app.js?v=20260717-resource-detail"></script></body></html>
