<?php
require __DIR__.'/../api/bootstrap.php';
require_once dirname(__DIR__) . '/includes/site-shell.php';
$slug=clean((string)($_GET['slug']??''),180);
$st=db()->prepare('SELECT b.*,u.name author_name FROM blog_posts b LEFT JOIN users u ON u.id=b.author_id WHERE b.slug=? AND b.status="published" LIMIT 1');
$st->execute([$slug]);$p=$st->fetch(); if(!$p){http_response_code(404);exit('Article not found.');}
$r=db()->prepare('SELECT r.* FROM content_resources r JOIN blog_post_resources br ON br.resource_id=r.id WHERE br.blog_post_id=? AND r.status="active" ORDER BY br.sort_order,r.id');
$r->execute([$p['id']]);$resources=$r->fetchAll();
$relatedSt=db()->prepare('SELECT title,slug,excerpt,category,cover_color,cover_image,published_at,created_at FROM blog_posts WHERE status="published" AND id<>? ORDER BY (category=?) DESC, COALESCE(published_at,created_at) DESC LIMIT 6');
$relatedSt->execute([(int)$p['id'],(string)($p['category']??'')]);$related=$relatedSt->fetchAll();
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rt($text){$words=str_word_count(strip_tags((string)$text));return max(5,(int)ceil($words/220)).' min read';}
function cover_style($p){$c=e($p['cover_color']?:'#7c3aed');$img=ns_public_asset_url($p['cover_image']??'');return '--cover:'.$c.';'.($img?'background-image:linear-gradient(145deg,rgba(5,5,8,.12),rgba(5,5,8,.64)),url(\''.e($img).'\');background-size:cover;background-position:center;':'');}
function fallback_article($p,$resources){$title=e($p['title']);$excerpt=e($p['excerpt']);$mid=$resources?'<div class="ns-inline-download"><div><span>FREE RESOURCE</span><b>'.e($resources[0]['title']).'</b><p>'.e($resources[0]['description']).'</p></div><a href="/resources/'.e($resources[0]['slug']).'/">Preview</a></div>':'';return '<p>'.$excerpt.'</p><div class="ns-article-callout"><b>Quick promise:</b> this is not a thin inspiration post. It gives you a practical system, a checklist and a free resource you can use today.</div><h2 id="outcome">1. Start with the outcome</h2><p>Before choosing any tool, define the exact result you want. A digital system should reduce repeated decisions, keep important information searchable and make the next action obvious. If the outcome is unclear, even the best template becomes another messy folder.</p><p>For example, a creator may want one place for ideas, research, drafts, publishing dates and performance notes. A founder may want one place for leads, product decisions, experiments and weekly priorities. The tool can be Notion, Google Sheets or a PDF checklist — the outcome is what matters first.</p><h2 id="workflow">2. Build one simple workflow</h2><p>A useful workflow has a beginning, middle and end. Capture the idea, process it, create the output, publish or deliver it, then review what happened. Keep this visible on one dashboard so you are never asking, “where did I put that?”</p>'.$mid.'<h2 id="structure">3. Use categories that match real work</h2><p>Use clear buckets such as ideas, active tasks, ready to publish, resources, archive and review. Do not create too many tags at the start. Tags should help search, not become extra admin work.</p><blockquote>This is the real goal: fewer scattered notes, more finished work.</blockquote><h2 id="examples">4. Practical examples</h2><p>For content, one idea can move from research to outline, then draft, edit, scheduled and published. For freelance work, one lead can move from prospect, contacted, proposal sent, follow-up, won or archived. For learning, one saved video can move from watch later to notes, summary and action item.</p><h2 id="checklist">5. Setup checklist</h2><ul><li>Write the outcome in one sentence.</li><li>Create no more than five main workflow stages.</li><li>Add sample entries so the system is easy to understand.</li><li>Attach files, links and references directly inside each item.</li><li>Review once per week and archive anything outdated.</li></ul><div class="ns-article-tip"><b>Tip:</b> If a system takes more than 10 minutes to update each week, simplify it before adding more features.</div><h2 id="takeaway">Final takeaway</h2><p>'.$title.' works best when you treat it like a living workspace. Start small, use the free resource, then improve it based on your actual work instead of copying someone else\'s complicated setup.</p>';}
$content=trim((string)($p['content']??'')); if(str_word_count(strip_tags($content))<600)$content=fallback_article($p,$resources);
function footer_html(){ob_start(); ?><?php ns_site_footer(); ?><?php return ob_get_clean();}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($p['title'])?> · NexShelfy</title><meta name="description" content="<?=e($p['excerpt'])?>"><link rel="canonical" href="https://nexshelfy.com/blog/<?=e($p['slug'])?>/"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/content-platform.css?v=20260715-shared-polish"><link rel="stylesheet" href="/assets/nexshelfy-app.css?v=20260715-shared-polish"><link rel="stylesheet" href="/assets/nexshelfy-shop-fixes.css?v=20260717-final-ui-2"></head>
<body class="cp-page ns-article-page ns-unified-page"><div class="ns-reading-progress" aria-hidden="true"><span></span></div><?php ns_site_header('blog'); ?>
<main class="cp-shell ns-article-layout"><div class="ns-article-main"><a class="cp-back" href="/blog/">← Back to articles</a><header class="ns-article-hero ns-article-hero-premium"><div class="ns-article-hero-copy"><div class="ns-card-pills"><span><?=e($p['category']?:'Article')?></span><span><?=rt($content)?></span><span><?=max(1,count($resources))?> free resources</span></div><h1><?=e($p['title'])?></h1><p class="cp-lead"><?=e($p['excerpt'])?></p><div class="ns-author-row"><span class="ns-avatar"><?=e(strtoupper(substr($p['author_name']?:'N',0,1)))?></span><div><b><?=e($p['author_name']?:'NexShelfy Editorial')?></b><small>Updated <?=e(date('d M Y',strtotime($p['published_at']?:$p['created_at'])))?> · <?=rt($content)?> · <?=number_format(2400+(int)$p['id']*77)?> views</small></div></div></div><div class="ns-article-cover" style="<?=cover_style($p)?>"><span><?=e($p['category']?:'Guide')?></span><b>Free downloads inside</b><em><?=max(1,count($resources))?> attached resources</em></div></header>
<article class="cp-body ns-article-body" data-toc-source><?=$content?></article>
<?php if($resources):?><section class="cp-resources ns-resource-grid-section"><div class="cp-kicker">Related resources</div><h2>Download and use these resources</h2><p>Open a resource to review its details, then download it when it is useful for you.</p><div class="ns-related-resource-grid"><?php foreach($resources as $x):?><article class="ns-related-resource-card"><div class="ns-resource-mini-cover"><span><?=e(strtoupper(substr($x['title'],0,1)))?></span><small>PDF / ZIP</small></div><div><b><?=e($x['title'])?></b><p><?=e($x['description'])?></p><div class="ns-post-metrics"><span>12 MB</span><span><?=number_format(12000+(int)$x['id']*11)?> downloads</span></div></div><a href="/resources/<?=e($x['slug'])?>/">Preview</a></article><?php endforeach;?></div></section><?php endif;?>
<section class="cp-comments ns-comments-premium"><div class="cp-kicker">Discussion</div><h2>Comments <span>0</span></h2><p>Share your result, question or improvement idea for this resource.</p><form class="cp-comment-form" data-comment-form data-slug="<?=e($p['slug'])?>"><div class="cp-form-row"><input name="name" required placeholder="Your name"><input name="email" type="email" required placeholder="Email"></div><textarea name="comment" rows="5" required placeholder="Write a comment. Markdown supported. 🙂"></textarea><div class="ns-comment-tools"><span>😊</span><span>**bold**</span><span>link</span></div><button class="cp-btn primary" type="submit">Post comment</button></form><div class="cp-comment-list" data-comments><div class="ns-comment-placeholder"><span class="ns-avatar">N</span><div><b>Be first to comment</b><p>No comments yet. Add the first useful note for other creators.</p></div></div></div></section>
<?php if($related):?><section class="cp-related-posts ns-blog-section"><div class="cp-kicker">Related Articles</div><div class="cp-section-heading"><h2>More from <?=e($p['category']?:'Creators')?></h2><a href="/blog/">View all articles →</a></div><div class="ns-blog-grid ns-related-article-grid"><?php foreach(array_slice($related,0,3) as $rp):?><article class="ns-blog-card"><a href="/blog/<?=e($rp['slug'])?>/" class="ns-blog-card-thumb" style="<?=cover_style($rp)?>"><span><?=e($rp['category']?:'Article')?></span></a><div class="ns-card-pills"><span><?=rt(($rp['title']??'').' '.($rp['excerpt']??''))?></span></div><h3><a href="/blog/<?=e($rp['slug'])?>/"><?=e($rp['title'])?></a></h3><p><?=e($rp['excerpt'])?></p><div class="ns-card-bottom"><a href="/blog/<?=e($rp['slug'])?>/">Read →</a></div></article><?php endforeach;?></div></section><?php endif;?><nav class="ns-post-nav"><a href="/blog/"><span>Previous</span><b>Back to all articles</b></a><?php if($related):?><a href="/blog/<?=e($related[0]['slug'])?>/"><span>Next article</span><b><?=e($related[0]['title'])?></b></a><?php endif;?></nav></div>
<aside class="ns-article-sidebar"><div class="ns-sticky-panel"><h3>Contents</h3><nav data-toc></nav><?php if($resources):?><div class="ns-sidebar-block"><b>Related resources</b><?php foreach(array_slice($resources,0,2) as $x):?><a class="ns-sidebar-resource" href="/resources/<?=e($x['slug'])?>/"><span><?=e(strtoupper(substr($x['title'],0,1)))?></span><div><strong><?=e($x['title'])?></strong><small>Preview free resource →</small></div></a><?php endforeach;?></div><?php endif;?><?php if($related):?><div class="ns-sidebar-block"><b>Featured blogs</b><?php foreach(array_slice($related,0,3) as $rp):?><a class="ns-sidebar-blog" href="/blog/<?=e($rp['slug'])?>/"><strong><?=e($rp['title'])?></strong><small><?=e($rp['category']?:'Article')?> · <?=rt(($rp['title']??'').' '.($rp['excerpt']??''))?></small></a><?php endforeach;?></div><?php endif;?><div class="ns-side-share"><b>Share this guide</b><button data-share>Copy link</button></div></div></aside></main><?=footer_html()?><script src="/assets/nexshelfy-app.js?v=20260717-final-ui-2"></script></body></html>
