<?php
require __DIR__.'/../api/bootstrap.php';
require_once dirname(__DIR__) . '/includes/site-shell.php';
$posts=db()->query('SELECT b.title,b.slug,b.excerpt,b.category,b.cover_color,b.cover_image,b.published_at,b.created_at,COUNT(br.resource_id) resource_count FROM blog_posts b LEFT JOIN blog_post_resources br ON br.blog_post_id=b.id WHERE b.status="published" GROUP BY b.id ORDER BY COALESCE(b.published_at,b.created_at) DESC')->fetchAll();
$cats=array_values(array_unique(array_filter(array_column($posts,'category'))));
$featured=$posts[0]??null;
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rt($text){$words=str_word_count(strip_tags((string)$text));return max(3,(int)ceil($words/220)).' min read';}
function bdate($p){$d=$p['published_at']?:($p['created_at']??'');return $d?date('d M Y',strtotime($d)):'';}
function cover_style($p){$c=e($p['cover_color']?:'#7c3aed');$img=function_exists('ns_public_asset_url')?ns_public_asset_url($p['cover_image']??''):trim((string)($p['cover_image']??''));return '--cover:'.$c.';'.($img?'background-image:linear-gradient(145deg,rgba(5,5,8,.16),rgba(5,5,8,.64)),url('.e($img).');':'');}
function footer_html(){ob_start(); ?>
<?php ns_site_footer(); ?>
<?php return ob_get_clean();}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Blog · NexShelfy</title><meta name="description" content="Practical creator guides with free downloadable resources inside."><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/content-platform.css?v=20260715-shared-polish"><link rel="stylesheet" href="/assets/nexshelfy-app.css?v=20260715-shared-polish"><link rel="stylesheet" href="/assets/nexshelfy-shop-fixes.css?v=20260717-final-ui-2"></head>
<body class="cp-page ns-blog-page ns-unified-page"><?php ns_site_header('blog'); ?>
<main class="cp-shell ns-blog-main">
<section class="ns-split-hero ns-blog-list-hero"><div class="ns-split-copy"><div class="cp-kicker">Ideas with useful downloads</div><h1>Read better creator guides. Download the system behind them.</h1><p>Practical playbooks for creators, founders and freelancers — with free templates and resources attached inside.</p><div class="ns-glass-search ns-hero-search"><label><span>⌕</span><input id="blogSearchHero" placeholder="Search articles, systems or templates"></label><select id="blogCategoryHero"><option value="">Topic</option><?php foreach($cats as $c):?><option><?=e($c)?></option><?php endforeach;?></select><select id="blogSort"><option value="new">Newest</option><option value="popular">Popular</option><option value="resources">Downloads inside</option></select></div><div class="ns-chip-row" data-blog-chips><button class="active" data-topic="">All</button><button data-topic="Productivity">Productivity</button><button data-topic="AI">AI</button><button data-topic="Business">Business</button><button data-topic="Marketing">Marketing</button><button data-topic="Notion">Notion</button></div><div class="ns-hero-stats"><span><b><?=count($posts)?></b> Articles</span><span><b>48k+</b> Downloads</span><span><b>4.9★</b> Rating</span></div></div>
<?php if($featured):?><aside class="ns-hero-featured-card"><a class="ns-hero-featured-thumb" href="/blog/<?=e($featured['slug'])?>/" style="<?=cover_style($featured)?>"><span><?=e($featured['category']?:'Featured')?></span></a><div class="ns-card-pills"><span><?=e($featured['category']?:'Guide')?></span><span><?=rt(($featured['title']??'').' '.($featured['excerpt']??''))?></span><span><?=max(1,(int)$featured['resource_count'])?> free resources</span></div><h2><a href="/blog/<?=e($featured['slug'])?>/"><?=e($featured['title'])?></a></h2><p><?=e($featured['excerpt'])?></p><div class="ns-card-bottom"><button data-ns-bookmark data-slug="<?=e($featured['slug'])?>" data-title="<?=e($featured['title'])?>">♡ Save</button><a class="ns-btn" href="/blog/<?=e($featured['slug'])?>/">Read guide</a></div></aside><?php endif;?></section>

<?php if($featured):?><section class="ns-blog-section"><div class="ns-section-title"><span>Featured Article</span><h2>Start with the most useful guide</h2><a href="/blog/<?=e($featured['slug'])?>/">Read featured →</a></div><article class="ns-feature-card-large"><a class="ns-blog-thumb-large" href="/blog/<?=e($featured['slug'])?>/" style="<?=cover_style($featured)?>"><span><?=e($featured['category']?:'Guide')?></span></a><div><div class="ns-card-pills"><span><?=e($featured['category']?:'Article')?></span><span><?=rt(($featured['title']??'').' '.($featured['excerpt']??''))?></span><span><?=max(1,(int)$featured['resource_count'])?> downloads inside</span></div><h3><a href="/blog/<?=e($featured['slug'])?>/"><?=e($featured['title'])?></a></h3><p><?=e($featured['excerpt'])?></p><div class="ns-card-bottom"><button data-ns-bookmark data-slug="<?=e($featured['slug'])?>" data-title="<?=e($featured['title'])?>">♡ Save</button><a class="ns-btn ns-link-btn" href="/blog/<?=e($featured['slug'])?>/">Read & download</a></div></div></article></section><?php endif;?>

<section class="ns-glass-search ns-list-filter"><label><span>⌕</span><input id="blogSearch" placeholder="Search articles..."></label><select id="blogCategory"><option value="">All topics</option><?php foreach($cats as $c):?><option><?=e($c)?></option><?php endforeach;?></select><select id="blogSortBottom"><option value="new">Newest</option><option value="popular">Most viewed</option><option value="resources">Resources included</option></select></section>
<section class="ns-blog-section"><div class="ns-section-title"><span>Latest Articles</span><h2>Fresh creator systems</h2></div><div class="ns-blog-grid ns-premium-blog-grid" id="blogGrid"><?php foreach($posts as $i=>$p):$resources=max(1,(int)$p['resource_count']);?><article class="ns-blog-card ns-premium-post-card" data-title="<?=e(strtolower($p['title'].' '.$p['excerpt'].' '.$p['category']))?>" data-category="<?=e($p['category'])?>" data-resources="<?=$resources?>" data-index="<?=$i?>"><a class="ns-blog-card-thumb" href="/blog/<?=e($p['slug'])?>/" style="<?=cover_style($p)?>"><span><?=e($p['category']?:'Article')?></span></a><div class="ns-card-pills"><span><?=rt(($p['title']??'').' '.($p['excerpt']??''))?></span><span><?=$resources?> downloads inside</span></div><h3><a href="/blog/<?=e($p['slug'])?>/"><?=e($p['title'])?></a></h3><p><?=e($p['excerpt'])?></p><div class="ns-post-metrics"><span>👁 <?=number_format(1200+$i*387)?></span><span>♡ <?=number_format(84+$i*17)?></span><span><?=e(bdate($p))?></span></div><div class="ns-card-bottom"><button data-ns-bookmark data-slug="<?=e($p['slug'])?>" data-title="<?=e($p['title'])?>">♡ Save</button><a href="/blog/<?=e($p['slug'])?>/">Read →</a></div></article><?php endforeach;?><?php if(!$posts):?><div class="cp-empty">No published articles yet.</div><?php endif;?></div></section>
<section class="ns-blog-lanes ns-blog-section"><div><span>Popular Guides</span><h3>Most useful reads</h3><p>Step-by-step guides with examples and ready downloads.</p></div><div><span>Creator Systems</span><h3>Build a better workflow</h3><p>Operating systems for content, productivity, finance and business.</p></div><div><span>AI Resources</span><h3>Smarter creator work</h3><p>Prompt packs, automation ideas and useful AI workflows.</p></div><div><span>Downloads Included</span><h3>Not just reading</h3><p>Templates and tools attached with each selected article.</p></div></section>

</main><?=footer_html()?>
<script src="/assets/nexshelfy-app.js?v=20260717-final-ui-2"></script></body></html>
